version: "3"
services: 
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql-container
        environment: 
            MYSQL_ROOT_PASSWORD: programadorabordo
        volumes: 
            - ./api/db/data:/var/lib/mysql
        restart: always
        networks: 
            - production-network

    api: 
        build: "./api"
        container_name: node-container
        restart: always
        volumes: 
            - ./api:/home/node/app
        ports: 
            - "9001:9001"
        depends_on: 
            - db
        networks: 
            - production-network
    
    web: 
        image: "php:7.2-apache"
        container_name: php-container
        restart: always
        volumes: 
            - ./website:/var/www/html
        ports: 
            - "8888:80"
        depends_on: 
            - db
            - api 
        networks: 
            - production-network
            
networks: 
    production-network: 
        driver: bridge

    
